# -*- coding: utf-8 -*-
# Giải thích câu trắc nghiệm Part 2 (Q11-15): {(test,q): text}
MC={
(1,11):"Người nói: \"the evening patrol route now includes the new shopping area because reports there have increased\" → A. B (giảm nhân viên) và C (tránh công trình) không được nhắc tới.",
(1,12):"\"do not confront anyone and do not post names online. The first step is to call the non-emergency police number\" → B. A (đăng lên mạng) và C (tiếp cận người lạ) đều bị người nói cấm – bẫy dạng phủ định.",
(1,13):"\"phones are the item reported missing most frequently, more often than wallets or bicycles\" → C. Wallets và bicycles được nhắc nhưng chỉ để so sánh (ít hơn phones).",
(1,14):"\"attach a visible identification sticker to the frame\" → A. B 'a second lock only' là bẫy: người nói chỉ nói ổ khóa chắc vẫn quan trọng chứ không đề xuất thêm khóa; C không được nhắc.",
(1,15):"\"from nine in the morning until one in the afternoon\" = 9:00–13:00 → B. Cần đổi giờ 12h sang 24h (1 p.m. = 13:00).",
(2,11):"\"our main aim is to shorten queue times, especially between ten and noon\" → A (queue times). Gift-shop và parking không được nhắc.",
(2,12):"\"Large tour groups should not block the lobby; please wait in the covered rear courtyard\" → B. Phòng triển lãm và máy bán vé không được nhắc.",
(2,13):"\"Guided walks are popular, so they now need to be booked in advance\" → A. Audio guides và bicycle hire không có thay đổi gì.",
(2,14):"\"The cafe has moved upstairs to the first floor, although its opening hours are unchanged\" → C. A sai vì giờ mở cửa không đổi; B không được nhắc.",
(2,15):"\"Local residents can collect printed city maps without charge\" → A (free = without charge). Museum entry và locker không được nhắc.",
(3,11):"\"Tuesday's boat trip will be a little shorter because strong winds are expected\" → A (high winds). Hướng dẫn viên và bến cảng không phải lý do.",
(3,12):"\"bring insect repellent; lunch is provided and walking poles are optional\" → B. A sai vì bữa trưa được cung cấp; C chỉ là tùy chọn (optional).",
(3,13):"\"Sea kayaking is designed for beginners, with a short lesson\" → A. Cliff climbing và deep-water diving không được nói là dành cho người mới.",
(3,14):"\"Thursday's special dinner will take place at the hotel rather than on the beach\" → B. Bẫy: 'on the beach' được nhắc nhưng bị loại bằng 'rather than'.",
(3,15):"\"everyone must watch the ten-minute safety video\" → C. Trả tiền mặt và xuất trình giấy tờ không được nhắc.",
(4,11):"\"focuses mainly on the history of Foxton Bay\" → B (Learning local history). Bird watching và photography không phải mục đích chính.",
(4,12):"\"that section can be cancelled if rain makes the narrow path unsafe\" → A. B và C không được nhắc là lý do hủy.",
(4,13):"\"Your ticket includes entry to the Harbour Museum, although lunch and binoculars are extra\" → C. A và B bị loại vì 'extra' (trả thêm).",
(4,14):"\"You can refill water bottles at the picnic field\" → B. Museum và lighthouse không được nhắc về nước uống.",
(4,15):"\"Guests staying at the holiday park receive a resident discount\" → C (park residents). Trẻ em và sinh viên không được nhắc.",
(5,11):"\"The oldest item in our collection is a newspaper edition printed in 1896\" → B. Camera và radio recording không được nhắc.",
(5,12):"\"strong light can damage fragile paper and photographs\" → B (damage old material). Paraphrase: fragile paper and photographs = old material.",
(5,13):"\"University students may book the editing suite for project work\" → A. Main studio và press office không được nhắc.",
(5,14):"\"At two o'clock there will be a practical photo workshop in Room 204\" → C. A và B không được nhắc.",
(5,15):"\"The archive shop sells reproduction posters based on famous front pages\" → B. Old cameras và used books không được bán.",
(6,11):"\"intended to introduce residents to the many local arts groups\" → B. Recruit staff và raise money không được nhắc.",
(6,12):"\"The songwriting workshop has only twenty places, so please book it\" → B (limited places). Các sự kiện khác không giới hạn chỗ.",
(6,13):"\"we provide the drums, but we recommend bringing ear protection\" → B. A sai vì trống do ban tổ chức cung cấp.",
(6,14):"\"Children who want to perform can use the Garden Stage\" → C. Small theatre là nơi trình diễn jazz (Q20), không phải của trẻ em.",
(6,15):"\"The final concert starts at half past six\" = 6:30 → C. Cần đổi 'half past six' thành 6:30.",
(7,11):"\"redesigned so that we can accept a wider range of household waste\" → A. Giờ mở cửa và cửa hàng không phải lý do.",
(7,12):"\"We take small electrical items and household batteries, but commercial refrigerators must be handled by a specialist contractor\" → B (NOT accepted). A và C được nhận.",
(7,13):"\"If you bring paint, please speak to a member of staff before unloading it\" → B. Không yêu cầu trộn màu hay bóc nhãn.",
(7,14):"\"The reuse shop is free to enter; delivery and repairs cost extra\" → C (entry). A và B phải trả thêm.",
(7,15):"\"The quietest time is usually early on Tuesday\" → A (least busy = quietest).",
(8,11):"\"particularly famous for migrating birds that stop here in spring and autumn\" → B. Butterflies và ancient trees không được nhắc ở câu này.",
(8,12):"\"temporarily closed because birds are nesting close to the trail\" → C (Bird nesting). Lưu ý đề đã đổi thứ tự phương án so với bản nguồn.",
(8,13):"\"You can borrow binoculars free of charge from the Visitor Centre\" → A. Raincoats và guidebooks không được nhắc.",
(8,14):"\"Please eat only in the picnic meadow\" → A (Only in the picnic area). Lưu ý đề đã đổi thứ tự phương án so với bản nguồn.",
(8,15):"\"If you see injured wildlife, tell a ranger immediately\" → B. Rác và thời tiết bất thường không được yêu cầu báo.",
(9,11):"\"Some international students need to check visa conditions before accepting paid work\" → A. Final-year students và students under 21 không được nhắc.",
(9,12):"\"The Job Centre has moved to the North Campus\" → A. Thư viện và trung tâm thể thao không phải vị trí mới.",
(9,13):"\"Our employment adviser is available on Fridays\" → C. Monday và Wednesday không được nhắc.",
(9,14):"\"will not automatically lead to a graduate position, but it can give you a useful work record\" → B. A và C không được đề cập; cẩn thận bẫy 'graduate position'.",
(9,15):"\"advertised through the weekly email bulletin\" → A. Áp phích và giảng viên không được nhắc.",
(10,11):"\"the company needs more space for new teams\" → A. Tiền thuê nhà và giao thông không phải lý do chính.",
(10,12):"\"most positive about the amount of natural light\" → A. Điều hòa và phòng yên tĩnh không được nhắc.",
(10,13):"\"The move will take place after the end of the tax year\" → B. Hội nghị bán hàng và kỳ nghỉ hằng năm không được nhắc.",
(10,14):"\"already has detailed public-transport information\" → C (bus and train information = public transport). Parking và nhà hàng không được nhắc.",
(10,15):"\"please take home personal belongings that do not need to move with you\" → A. B và C không được yêu cầu.",
(11,11):"\"Please bring photo identification to the registration desk\" → A. Biên lai tiền mặt và giấy chứng nhận thuyền không được yêu cầu.",
(11,12):"\"Your entry fee includes Saturday dinner, but equipment and boat fuel are extra\" → B. A và C bị loại vì 'extra'.",
(11,13):"\"If you do not already have a fishing licence, apply online before you arrive\" → C. Không phải tại bàn đăng ký hay qua điện thoại.",
(11,14):"\"Fishing finishes at six o'clock on Sunday evening; judging starts shortly afterwards\" → A. B (judging begins) là bẫy: xảy ra 'shortly afterwards', không phải đúng 6 giờ.",
(11,15):"\"Anyone using a boat must wear a life jacket at all times\" → A. B và C không được nhắc.",
(12,11):"\"please use the shopping-centre car park; the sports ground is reserved for emergency vehicles\" → C. Sports ground bị loại (dành cho xe khẩn cấp).",
(12,12):"\"Your timing chip must be attached securely to your shoe\" → A. Cổ tay và áo không được nhắc.",
(12,13):"\"The red group starts first, followed by yellow and then purple\" → B. Bẫy thứ tự: yellow và purple đến sau.",
(12,14):"\"We still need volunteers at the water stations, while first aid and the starting line are fully staffed\" → B.",
(12,15):"\"Large bags should go to the official bag-drop area rather than being carried to the start\" → B. Không để trong xe, không mang ra vạch xuất phát.",
}
