S={}
def a(n,ans,topic,exp): S[n]=(ans,topic,exp)
# ---- Module 1: Modals and similar expressions (Ch.2)
a(1,'B','Past modal – should have + V3','Phòng ngủ sơn đen trông ảm đạm → người nói chê trách lựa chọn trong quá khứ: should have chosen (lẽ ra nên chọn). "must have chosen" là suy đoán, không hợp nghĩa; "had to choose" nói về sự bắt buộc.')
a(2,'B','Modal – should be + V-ing','(Câu có hai đáp án hợp lý – không dùng trong đề.)')
a(3,'D','Past ability – could','"When Mr. Lee was younger" + "for hours": khả năng/thói quen làm việc trong quá khứ nay không còn → could work. "can" sai thì; "has got to" chỉ sự bắt buộc ở hiện tại.')
a(4,'A','Would – repeated past action','"Whenever my parents went out" diễn tả hành động lặp lại trong quá khứ → would get. "should/had better" là lời khuyên, "must have gotten" là suy đoán.')
a(5,'B','Simple past (no modal)','"Yesterday I … I bought a new lamp there": sự việc có thật đã xảy ra → simple past went. Các dạng could/ought to have gone nói về điều không xảy ra.')
a(6,'B','Used to – past habit','Hai đứa trẻ nghịch ngợm thường chơi khăm giáo viên trong quá khứ → used to play. "could"/"may have played" không diễn tả thói quen lặp lại.')
a(7,'D','Was able to – one specific past achievement','Thành công trong một lần mua cụ thể ("paid 30 percent less") → was able to buy. "could" chỉ dùng cho khả năng chung trong quá khứ, không dùng cho thành tích một lần ở câu khẳng định.')
a(8,'A','Would rather + base form','"would rather" + V nguyên mẫu để nói sở thích: I\'d rather go to a movie. B, C, D sai dạng động từ sau would rather.')
a(9,'C','Past deduction (negative) – couldn\'t have + V3','Có bằng chứng ngoại phạm ("I was with her") → suy luận chắc chắn cô ấy không thể đã phạm tội: couldn\'t have committed. "may not have" chỉ là khả năng yếu.')
a(10,'A','Had better – strong advice','Tình huống gấp ("have to be there in a hurry") → lời khuyên mạnh: we had better take a taxi. "may/are able to" không hợp nghĩa; "have been used to" sai cấu trúc.')
a(11,'D','Might – future possibility','Khả năng yếu về tương lai gần: It might rain this evening (nên mang ô). "must" quá chắc chắn, "had better" không đi với chủ ngữ "it" ở nghĩa này.')
a(12,'C','Polite request – will you','Yêu cầu lịch sự người khác làm gì: Will you hand me…? "May" dùng xin phép cho chính mình; "Shall/Should" không dùng để yêu cầu.')
a(13,'C','Past deduction – must have + V3','Lái xe cả đêm → suy luận chắc chắn về quá khứ: must have been exhausted. "will have been" dùng cho tương lai.')
a(14,'D','Be supposed to – expectation','Theo kế hoạch họ phải đến sau ba giờ nữa → aren\'t supposed to be here. "couldn\'t/had better not" không hợp nghĩa.')
a(15,'C','Would you mind + V-ing','Mẫu lịch sự "Would you mind + V-ing?" (trả lời "Not at all"). A, B, D không đi với V-ing.')
a(16,'A','Could have + V3 – unused past possibility','Điều có thể làm nhưng không làm trong quá khứ: You could have called your roommate. "would have" cần mệnh đề if; "must/may have" là suy đoán.')
a(17,'D','Must – strong deduction','Không ăn từ hôm qua → suy luận chắc chắn: You must be really hungry. "might/can" quá yếu hoặc sai nghĩa.')
a(18,'C','Future (will have been)','"on our next anniversary" → mốc tương lai: We will have been married for 23 years. Chỉ "will" tạo được thì tương lai hoàn thành.')
a(19,'C','Be supposed to – expectation/arrangement','Đã có sắp xếp phải có mặt lúc 6 giờ: I am supposed to be there. "will be/may be" không diễn tả nghĩa vụ, "have got to be" thiếu logic về nghĩa.')
a(20,'A','Past possibility – may have + V3','Không biết chắc ai ăn → khả năng yếu về quá khứ: may have eaten. "had to eat/should have eaten" nói về bắt buộc hoặc chê trách.')
a(21,'A','Shouldn\'t – expectation','"That shouldn\'t bother you" = đáng lẽ điều đó không nên làm bạn khó chịu ("But it does" – nhưng thực tế có). "won\'t/may not" không hợp văn cảnh.')
a(22,'B','Why don\'t we – suggestion','Đề nghị đi về khi phim dở: Why don\'t we leave? "Will we/Would we" không dùng để gợi ý; "Must we" là than phiền.')
a(23,'A','Had better – warning','Cá sắp hỏng → lời khuyên mạnh có hậu quả: had better put it in the refrigerator. "had to" là quá khứ; "may put" không phải lời khuyên.')
a(24,'C','Don\'t have to – lack of necessity','Ông ấy giàu nên không cần phải đi làm: doesn\'t have to work. "must not" là cấm; "hadn\'t better" không dùng.')
a(25,'A','Had to – past necessity','"Why are you so late?" → lý do bắt buộc trong quá khứ: I had to take my aunt to the airport. "must have taken" là suy đoán của người khác, không dùng với chủ ngữ I ở nghĩa này.')
a(26,'C','Must – deduction (present)','Được mời làm việc tốt → suy luận hợp lý: She must be very pleased. "is supposed to / might be" không phù hợp mức độ chắc chắn.')
a(27,'A','Used to – past habit','"When I had my farm" – thói quen trong quá khứ đã chấm dứt: I used to work. "ought to/must/had better" nói về nghĩa vụ hiện tại.')
a(28,'B','Should not have + V3 – criticism','Xe bị kéo đi vì đỗ sai chỗ → chê trách hành động đã làm: You should not have parked there. "must not have" sai nghĩa (suy đoán), "may/might not have" chỉ khả năng.')
a(29,'C','Will – future fact','Năm sau ông 50 tuổi: sự thật chắc chắn trong tương lai → will be. "should/must/has to" không phù hợp.')
a(30,'C','Polite request – could','Yêu cầu lịch sự người khác giúp: Could you lift…? "May" xin phép; "Shall/Should" không dùng để yêu cầu.')
a(31,'D','Past deduction – couldn\'t have + V3','Số không có trong danh bạ → bạn không thể đã tìm thấy nó: you couldn\'t have found it. "won\'t" không dùng cho quá khứ; "may/might not have" chỉ khả năng yếu.')
a(32,'C','Could – future possibility','Theo chuyên gia, núi lửa có thể phun trở lại → could erupt. "may be erupt" sai ngữ pháp; "would/had better" không phù hợp nghĩa.')
a(33,'A','Past ability – could','"Last year I could read … but now I can\'t": khả năng trong quá khứ nay không còn. "must/should have read" sai nghĩa.')
a(34,'B','Must not – prohibition','Luật cấm xả rác → must not throw. "don\'t have to" = không cần thiết, nghĩa khác hẳn.')
a(35,'C','Would rather + base form','would rather go (V nguyên mẫu, không to/ing).')
a(36,'A','Have got to – necessity','"We need her there" → bắt buộc mạnh: She has got to go. "has gotten to/have to" sai dạng; "must be go" sai cấu trúc.')
a(37,'B','Would you mind + V-ing','Mẫu "Would you mind letting me…?" (đáp "Not at all"). "Please to" sai ngữ pháp.')
a(38,'D','Be supposed to (negative) – rule/expectation','Biển "No Trespassing" → chúng ta không được phép ở đây: aren\'t supposed to be here. "couldn\'t/might not" không diễn đạt quy định.')
a(39,'C','Should have + V3 – criticism','Áo không vừa → đáng lẽ anh ấy nên thử trước khi mua: should have tried. "must have tried" mâu thuẫn với việc áo không vừa.')
a(40,'A','Would – repeated past action','"When I worked at the embassy… every afternoon": hành động lặp lại trong quá khứ → would meet. "would rather" có nghĩa khác.')
# ---- Module 2: The passive (Ch.3)
a(41,'A','Passive – simple past','Xe đạp bị lấy cắp (chủ thể không quan trọng) → was stolen. "stolen" thiếu be; "stole/was stealing" là chủ động.')
a(42,'C','Passive – present progressive','Vấn đề đang được nghiên cứu → is being studied (be + being + V3). "being studying", "been studied" sai cấu trúc.')
a(43,'A','Intransitive verb – no passive','"happen" là nội động từ, không có bị động → happened. "was happened/is happened" sai.')
a(44,'C','Passive – past perfect','Bị ong đốt xảy ra trước khi tay sưng → had been stung (had + been + V3).')
a(45,'D','Passive with modal','Bệnh được ngăn ngừa nhờ tiêm chủng → can be prevented (modal + be + V3). "can prevent" là chủ động.')
a(46,'D','Stative verb – active only','"agree" không dùng bị động và không đi với "am" → I agree with you.')
a(47,'C','Passive – simple present','Ô tô được sản xuất ở Detroit → are manufactured (chủ thể không cần nêu).')
a(48,'D','Passive – future','Không điều gì sẽ đạt được nhờ chờ đợi → will be accomplished. Các đáp án khác là chủ động hoặc sai thì.')
a(49,'C','Passive question','Câu hỏi bị động Wh-: When was penicillin discovered? (be đứng trước chủ ngữ).')
a(50,'B','Passive with modal','must + be + V3 + with: must be equipped with. "equip by/with" thiếu be hoặc sai giới từ.')
a(51,'A','Passive – present progressive','Nước đang bị lấy lên liên tục "faster than nature can replenish" → is being taken.')
a(52,'C','Passive – simple present','Vitamin C được cơ thể hấp thụ → is easily absorbed (trạng từ đứng giữa be và V3).')
a(53,'B','Passive after will','"it\'ll be finished late this afternoon" – xe sẽ được sửa xong. "finish" cần tân ngữ nếu chủ động.')
a(54,'D','Get-passive','"got hired" = được tuyển; get + V3 là dạng bị động thông tục. "got hiring" sai.')
a(55,'B','Be dedicated to','Cụm cố định be dedicated to + danh từ/V-ing: My country is dedicated to the pursuit…')
a(56,'C','Passive – simple past','"15,000 years ago" → quá khứ đơn bị động: was buried under ice.')
a(57,'A','Participial adjective (V3)','established routine = thói quen đã được thiết lập; phân từ quá khứ làm tính từ.')
a(58,'B','Active – simple past','The Mayan Indians (chủ thể) developed a calendar → chủ động. "were developed" sai nghĩa.')
a(59,'D','Be married to','Cụm cố định be married to someone.')
a(60,'A','Passive – simple past','Những người cứu hộ được khen ngợi → were praised for…')
a(61,'C','Passive – present progressive','"right now" → Something is being done right now.')
a(62,'B','-ing vs -ed adjective','Cuộc sống dưới biển "gây" hứng thú → fascinating. "fascinated" dùng cho người cảm thấy.')
a(63,'A','Passive – simple present','Trường đại học được tài trợ bởi quỹ tư nhân → is supported by…')
a(64,'B','Active – simple past','"the mechanic … discovered the source of the problem" – chủ động; "was discovered" sai vì người thợ là chủ thể.')
a(65,'B','Passive – present perfect','They\'ve already been typed (thư đã được đánh máy).')
a(66,'A','Active – present progressive','"They are still considering the proposal" – ủy ban là chủ thể → chủ động.')
a(67,'B','Passive – present progressive','Dịch vụ y tế đang được cung cấp bởi số ít nhân viên → is being provided by…')
a(68,'A','Get-passive in a question','How did that window get broken? Sau trợ động từ did dùng get nguyên mẫu; got ở C sai.')
a(69,'C','Passive – simple present','Tranh của Renoir được xem là kiệt tác → are considered.')
a(70,'C','Passive – simple past','Hoàng tử bị phù thủy biến thành ếch → was turned into a frog.')
a(71,'D','Passive – past perfect','had been lightly covered with snow.')
a(72,'A','Participial adjective + preposition','be protected from + noun (được bảo vệ khỏi gió).')
a(73,'C','Passive question – present perfect','Has an announcement been made…? (trợ động từ đứng trước chủ ngữ).')
a(74,'A','Active – simple past','"A tornado … It destroyed everything" – chủ động; chủ ngữ it là cơn lốc.')
a(75,'C','Passive with modal','can + be + V3: can be found (cặn thuốc trừ sâu có thể được tìm thấy).')
a(76,'A','Passive – simple past','Cuối cùng cây cầu được xây dựng → was constructed.')
a(77,'B','Passive – present progressive','Đường cao tốc đang bị chặt kín người → are being crowded by people.')
a(78,'C','Passive – past perfect','Hệ thống điều hòa đã được lắp trước khi đợt nóng đến → had been installed.')
a(79,'A','Passive – simple past','Đơn xin học bổng bị từ chối → was denied.')
a(80,'B','Passive with perfect modal','should have been called (lẽ ra bác sĩ nên được gọi).')
# ---- Module 3: Gerunds and infinitives (Ch.4)
a(82,'A','Gerund after preposition','Sau giới từ "for" dùng V-ing; dạng phủ định "not" đứng trước: for not wanting to go.')
a(83,'B','Verbs of perception + V-ing','hear + O + V-ing: hear someone trying to open (đang cố mở).')
a(84,'D','Gerund after "deny" (passive)','deny + V-ing; ở đây là bị động "bị liên can" → being involved.')
a(85,'A','Gerund with possessive','Sau giới từ "by": possessive + (not) having + V3 → by our not having told him.')
a(86,'B','Gerund after "consider"','consider + V-ing; "go shopping" → going shopping.')
a(87,'D','Infinitive after "offer"','offer + to V → offered to take care of.')
a(88,'C','Need + O + infinitive','need + O + to V (+ V nguyên mẫu sau help) → to help me move.')
a(89,'A','Gerund after "avoid"','avoid + V-ing. (Đáp án gerund hoàn thành không tự nhiên – không dùng trong đề.)')
a(90,'D','Participle of simultaneous action','stood there admiring = đứng đó và ngắm; V-ing chỉ hành động đồng thời.')
a(91,'A','Instead of + gerund','Giới từ "instead of" + V-ing: instead of trying.')
a(92,'B','Gerund (perception verb) as subject','Watching it land was frightening: cụm V-ing làm chủ ngữ, "watch + O + V nguyên mẫu".')
a(93,'D','Infinitive of purpose','to see = để xem (mục đích).')
a(94,'B','Have trouble + gerund','have trouble + V-ing: have trouble separating fact from fiction.')
a(95,'B','Excuse for + gerund','Sau giới từ for dùng V-ing: an excuse for being late.')
a(96,'C','Make + O + base form','make + O + V nguyên mẫu (không to): made me promise to call.')
a(97,'C','Get + O + infinitive','get + O + to V: got Barbara to let me borrow.')
a(98,'D','Forget + gerund','forget + V-ing = quên chuyện đã xảy ra: never forget winning that race.')
a(99,'C','Passive infinitive after adjective','certain + to V; Carol "được chọn" → to be chosen.')
a(100,'A','Stop + gerund / infinitive of purpose','stopped reading (ngừng đọc) to watch (để xem).')
a(101,'B','Recall + gerund','recall + V-ing: don\'t recall seeing her.')
a(102,'D','By + gerund','by + V-ing: by producing two witnesses.')
a(103,'D','Have a difficult time + gerund','have a difficult time + V-ing: opening it.')
a(104,'A','Passive infinitive after "demand"','demand + to V; ở đây bị động → demanded to be heard.')
a(105,'B','Gerund after "finish"','finish + V-ing: finish designing.')
a(106,'B','Go + V-ing','go + V-ing cho hoạt động giải trí: go sailing.')
a(107,'C','Infinitive of purpose','to repair = để sửa (mục đích). "for repairing" cần tân ngữ khác.')
a(108,'C','Passive gerund after "like"','like + V-ing; người nói bị lừa → being deceived.')
a(109,'C','Make + O + base form','make + O + V nguyên mẫu: makes her students view.')
a(110,'B','Remember + infinitive','remember + to V = nhớ để làm việc cần làm: remember to raise your hand.')
a(111,'A','It + adjective + infinitive','It is important + to V: to take care of.')
a(112,'D','Gerund as subject','V-ing làm chủ ngữ: Eating in restaurants … is expensive.')
a(113,'A','Expect + O + infinitive','expect + O + to V: expect Mary to come.')
a(114,'B','Advise + O + (not) to V','advise + O + (not) to V: not to marry.')
a(115,'D','Verbs of perception + V-ing','hear someone shouting (đang nghe thấy tiếng hét).')
a(116,'A','Possessive + gerund','understand + possessive + V-ing: your quitting.')
a(117,'C','See + O + base form','see + O + V nguyên mẫu (thấy toàn bộ sự việc): saw a meteor streak.')
a(118,'D','Let + O + base form','let + O + V nguyên mẫu: wouldn\'t let me stay.')
a(119,'C','Passive of encourage + infinitive','be encouraged + to V: to develop.')
a(120,'D','Need + have + O + V3 (causative)','need to have it painted = cần thuê/nhờ sơn.')
a(121,'D','Regret + perfect gerund','regret + not having + V3 = hối tiếc đã không làm: not having finished college.')
# ---- Module 4: Connecting ideas / adverb clauses (Ch.8)
a(122,'B','Time clause – as soon as','As soon as Paul brings the money = ngay khi Paul mang tiền đến, ta sẽ xuống căng-tin.')
a(123,'B','(Lỗi nguồn)','(Không dùng trong đề.)')
a(124,'B','(Lỗi nguồn)','(Không dùng trong đề.)')
a(125,'D','Reduced adverb clause','"When you use" rút gọn thành When using a dictionary (cùng chủ ngữ).')
a(126,'C','Sentence connection','Hai câu độc lập tách bằng dấu chấm: …fascinating animals. They have… (A thiếu logic, B comma splice, D là mệnh đề phụ thiếu mệnh đề chính).')
a(127,'D','Reduced adverb clause','While + V-ing (While I was trying → While trying), cùng chủ ngữ "I".')
a(128,'A','Due to + noun phrase','Due to + cụm danh từ (extremely bad weather). Because/Since/Due to the fact that cần một mệnh đề.')
a(129,'C','Because + clause','because + S + V: … because she knows… "therefore/so" cần cấu trúc khác; "because of" cần danh từ.')
a(130,'B','Conjunctive adverb – consequently','Gãy chân → kết quả phải bó bột: Consequently, … (trạng từ nối chỉ kết quả).')
a(131,'A','So + little … that','so little money available that… (money không đếm được → little, không dùng such little).')
a(132,'B','Due to + noun phrase','due to land development and the grazing… (cụm danh từ).')
a(133,'C','Since – time','(Không dùng trong đề.)')
a(134,'A','Yet – contrast','Joe có vẻ vui nhưng lại gắt gỏng → yet (nhưng) chỉ sự tương phản.')
a(135,'A','By the time','By the time + hiện tại đơn, + tương lai hoàn thành: By the time Jan arrives, we will have finished.')
a(136,'B','Parallel structure','Cấu trúc song song: playing, eating, and sleeping.')
a(137,'D','So that – purpose','so that + S + could/can + V để chỉ mục đích: so that she could earn money.')
a(138,'A','Reduced adverb clause','Being unprepared = Because I was unprepared (rút gọn cùng chủ ngữ).')
a(139,'C','Ever since','(Không dùng trong đề.)')
a(140,'C','Once – time clause','Once my daughter reaches sixteen = Khi/Một khi con gái tôi 16 tuổi (mệnh đề thời gian, hiện tại đơn).')
a(141,'C','Now that – reason','now that he has had skiing lessons = vì bây giờ anh ấy đã học trượt tuyết.')
a(142,'C','As long as – condition','As long as it\'s warm and sunny today = miễn là/vì trời ấm và nắng, thì mình đi công viên.')
a(143,'D','Now that – reason','Now that I\'ve learned to stay afloat = giờ đây khi tôi đã biết nổi, tôi thấy thoải mái hơn.')
a(144,'C','Neither … nor','neither the workers nor the manager intends (động từ chia theo danh từ gần nhất: manager → intends).')
a(145,'B','Due to + noun phrase','due to his inability to concentrate (cụm danh từ).')
a(146,'C','Reduced adverb clause','After + V-ing: After listening to 45 minutes of… (cùng chủ ngữ).')
a(147,'A','The next time','The next time I am in that situation = lần tới khi tôi ở trong tình huống đó.')
a(148,'D','Yet – contrast','Trời lạnh cóng nhưng bạn mặc quần short → yet (nhưng).')
a(149,'B','Parallel structure','likes to swim, jog, and play tennis (V nguyên mẫu song song).')
a(150,'C','Since + V-ing','Since moving to… = Kể từ khi chuyển đến…')
a(151,'D','So much … that','so much money that he didn\'t have enough left.')
a(152,'A','Once – time clause','Once I get back from my next trip, I\'m taking a few days off.')
a(153,'D','Whenever','whenever the temperature gets near freezing = mỗi khi nhiệt độ gần đóng băng.')
a(154,'D','Before + V-ing','Before accepting a promotion… (rút gọn cùng chủ ngữ I).')
a(155,'A','So that – purpose','so that you can handle an emergency = để bạn có thể xử lý.')
a(156,'B','Therefore','Therefore, = Vì vậy (trạng từ nối chỉ kết quả, sau dấu chấm).')
a(157,'C','Participial phrase','Not wanting to be late… I ran → mệnh đề chính có chủ ngữ I. (Không thêm so/because/therefore sau cụm phân từ.)')
a(158,'B','So … that – result','so hard that I couldn\'t go outside (adj/adv + that).')
a(159,'A','Due to + noun phrase','due to the rotation of the earth (cụm danh từ).')
a(160,'D','Sentence connection','…dangerous to humans. They will attack without warning. (Hai câu độc lập tách bằng dấu chấm.)')
a(161,'C','Because of + noun phrase','Because of the need to finish… (cụm danh từ).')
# ---- Chapter 9 (m2 index 162-201): Showing relationships between ideas
a(162,'C','Condition – provided that','Provided that + S + V = với điều kiện/miễn là (điều kiện đủ để chấp nhận). "Due to" cần danh từ; "unless" mang nghĩa phủ định.')
a(163,'D','Such as – examples','such as + danh từ = ví dụ như (coal, oil, water, steam). "as" không dẫn ví dụ; "and they use" thừa động từ.')
a(164,'C','In addition to + noun','In addition to + cụm danh từ = ngoài ... ra (thêm thông tin cùng chiều). "In spite of" chỉ sự đối lập.')
a(165,'A','In spite of + noun','Dù có nhiều tiến bộ công nghệ vẫn cần biết đánh máy → nhượng bộ: In spite of the many technological advances.')
a(166,'A','Due to + noun','Vịt khô ráo là NHỜ lớp dầu → nguyên nhân: due to the oil on its feathers.')
a(167,'D','Unless – negative condition','He will never advance unless he improves = nếu anh ấy không cải thiện thì sẽ không thăng tiến.')
a(168,'B','Even though – contrast','Không có điện nhưng vẫn đọc được → even though + clause (nhượng bộ). "Even" một mình không nối mệnh đề.')
a(169,'C','Otherwise','Otherwise, it will stop burning = nếu không (có oxy) thì lửa sẽ tắt.')
a(170,'D','Nevertheless – contrast','Học tiếng Tây Ban Nha 4 năm, tuy nhiên vẫn khó giao tiếp → Nevertheless.')
a(171,'C','In the event that','in the event that you change your mind = trong trường hợp bạn đổi ý (điều kiện có thể xảy ra).')
a(172,'C','On the other hand – contrast','Đối lập giữa tôi và vợ: My wife, on the other hand, prefers a warm bedroom.')
a(173,'A','Whereas – contrast','whereas nối hai vế tương phản: Some fish… salt water, whereas other species… fresh water.')
a(174,'B','Ever since','Ever since Jason became famous = kể từ khi, kết hợp với thì hiện tại hoàn thành (has ignored).')
a(175,'B','Unless','We\'re going to lose unless the team starts playing better = trừ khi đội chơi tốt hơn.')
a(176,'C','Even if','Even if the food is terrible, I\'m going to enjoy… = dù cho món ăn dở, tôi vẫn vui.')
a(177,'D','But – contrast','Anh ta khăng khăng không cần giúp, nhưng tôi vẫn giúp → but.')
a(178,'B','Furthermore – addition','Bãi biển đẹp; Furthermore, thời tiết ấm áp = hơn nữa (thêm ý cùng chiều).')
a(179,'B','Now that','now that winter is gone = vì bây giờ mùa đông đã qua (lý do).')
a(180,'A','Only if + inversion','Only if đứng đầu câu thì mệnh đề chính đảo trợ động từ: Only if you promise… will I agree.')
a(181,'B','However – contrast','The Arabian camel has one hump. The Bactrian camel, however, has two humps (đối lập).')
a(182,'D','Only if','He will not agree … only if he is convinced = chỉ khi nào được thuyết phục.')
a(183,'B','Even though – contrast','Cùng phát âm dù viết khác nhau → even though.')
a(184,'D','In addition to + noun','In addition to olives, cooking oil can be extracted from coconuts… (thêm nguồn khác).')
a(185,'C','For – reason (conjunction)','for = bởi vì (liên từ nối mệnh đề lý do): …, for I didn\'t have any coins.')
a(186,'C','Otherwise','Otherwise, I get grouchy… = nếu không ăn sáng thì tôi cáu kỉnh.')
a(187,'A','Provided that','Provided that I can find one… (điều kiện); "only if" ở giữa câu cần cấu trúc khác.')
a(188,'D','Because of + noun','because of its high fat content (nguyên nhân – cụm danh từ).')
a(189,'C','Contrast with "but"','Hai vế đối lập nối bằng but: I want to take a train trip…, but my companion wants to fly.')
a(190,'B','Nevertheless – contrast','Nhiều kinh nghiệm, nevertheless vẫn gặp vấn đề không tự giải quyết được.')
a(191,'A','In the event that','In the event that there is a cancellation, I will call you.')
a(192,'A','However – contrast','A newborn antelope, however, can run… (đối lập với em bé).')
a(193,'A','Only if','(Có hai phương án hợp lý – không dùng trong đề.)')
a(194,'D','Even though – contrast','Bị cháy nắng dù đội mũ rộng vành → even though.')
a(195,'A','Only if','You should go … only if you like that kind of music = chỉ khi bạn thích.')
a(196,'A','On the other hand – contrast','Peter chăm chỉ; his brother, on the other hand, ít cố gắng.')
a(197,'B','In spite of + noun','He never smiles … in spite of the many efforts I have made (nhượng bộ).')
a(198,'B','Furthermore – addition','Furthermore, there will be poetry readings = hơn nữa (bổ sung).')
a(199,'D','But – contrast','Bánh mì cũ nhưng Martha vẫn ăn → but.')
a(200,'B','Such as – examples','Minerals such as nickel, copper, and zinc.')
a(201,'D','Only if + inversion','Only if you get there early will you have a chance… (đảo trợ động từ sau mệnh đề only if).')
# ---- Chapter 10 (m2 index 202-241): Conditional sentences and wishes
a(202,'B','As though – past unreal','as though he had read my mind = như thể anh ấy đã đọc được ý nghĩ của tôi (past perfect cho điều trái thực tế trong quá khứ).')
a(203,'C','Past unreal condition (progressive)','Điều kiện không có thật ở quá khứ: If you hadn\'t been studying, I would have brought my friends (vì bạn đang học nên tôi không rủ).')
a(204,'C','Wish – present','wish + could + V = ước có thể (hiện tại): I wish I could lend you some money.')
a(205,'A','Real condition + imperative','If + hiện tại đơn, mệnh lệnh: If someone comes into the store, smile…')
a(206,'C','Wish – past','wish + had + V3 = ước điều đã không xảy ra: I wish we had brought a map.')
a(207,'B','Real future condition','If + hiện tại đơn, will + V: if I need some help tomorrow.')
a(208,'D','Present unreal condition','If I weren\'t working…, I would be working in a bank (would + be + V-ing).')
a(209,'B','Mixed conditional','Mixed: If + had V3 (quá khứ), would + V (hiện tại): He wouldn\'t be in this position now if he had listened.')
a(210,'D','Mixed conditional','If we had known (quá khứ), the world might be a better place (hiện tại).')
a(211,'A','As though – present unreal','as though the room were spinning (were cho điều không có thật ở hiện tại).')
a(212,'C','Past unreal condition','you wouldn\'t have done it if you hadn\'t had to = nếu bạn không bị buộc phải làm.')
a(213,'B','Inverted conditional (Were I)','Were I you = If I were you (đảo ngữ, không có if).')
a(214,'B','Past unreal result','It would have been much worse if she hadn\'t been wearing a seatbelt.')
a(215,'B','Mixed conditional','If my candidate had won (quá khứ), I would be happy now (hiện tại).')
a(216,'D','Wish – future/present','wish + could/would + V: I wish Janet could come to the meeting.')
a(217,'C','Would have + V3','Điều định làm nhưng không làm ở quá khứ: I would have introduced you… but I couldn\'t think of her name.')
a(218,'D','Mixed conditional question','What would you be doing today if you hadn\'t come here? (would + be + V-ing).')
a(219,'D','Inverted conditional (Should)','Should you have any problem = If you should have any problem (đảo ngữ trang trọng).')
a(220,'D','Implied condition – otherwise','Otherwise = nếu không (đã rời đi) → might have said (khả năng ở quá khứ).')
a(221,'A','Inverted conditional (Had I known)','Had I known = If I had known (đảo ngữ, quá khứ).')
a(222,'D','Real condition','If you continue to talk loudly, I will have to ask you to leave (điều kiện có thật).')
a(223,'D','Wish – present','wish + quá khứ đơn: I wish I had her energy.')
a(224,'A','Past result of present unreal','If he were qualified (hiện tại), he would have been given that promotion last year.')
a(225,'C','Present unreal condition','If I could find Rob\'s number, I could call him (could = có khả năng).')
a(226,'C','Wish – past','wish + had V3: I wish I had gotten used to the noise (ước điều đã không xảy ra).')
a(227,'A','As though – present unreal','as though we were there (như thể chúng tôi đang ở đó).')
a(228,'D','Past unreal condition','If I hadn\'t been following too closely, I would have been able to stop.')
a(229,'B','Present unreal condition','If I were brave, I would go with you.')
a(230,'A','Should in if-clause','if I should see him later, I\'ll give your message = nếu tình cờ gặp.')
a(231,'C','Wish – past','I wish I hadn\'t had to take Bob = ước đã không phải đưa Bob.')
a(232,'D','Implied condition – otherwise','Otherwise, we\'re going to miss the opening ceremony (dự đoán tương lai).')
a(233,'B','Past unreal result','I would have told you, but… (đã không nói).')
a(234,'D','Real/general condition','Sự thật chung: if it spends more money on imports → spends (hiện tại đơn).')
a(235,'C','Inverted conditional (Should)','Should something go wrong = If something should go wrong.')
a(236,'B','Inverted conditional (Had I known)','Had I known… I would have gotten the materials (past unreal).')
a(237,'A','Wish – would','wish + would + V = muốn ai đó dừng hành động gây khó chịu.')
a(238,'B','Inverted conditional (Had I been)','Had I been in the room, I would have been killed.')
a(239,'D','Present unreal condition','If everyone could fly, how would we control air traffic?')
a(240,'C','Real future condition','If forests continue to disappear, many species will become extinct.')
a(241,'A','As if – past','as if a heavy weight had been lifted from my shoulders (past perfect bị động).')
