S={}
def a(n,ans,topic,exp): S[n]=(ans,topic,exp)
# ---- Module 1: Modals and similar expressions (Ch.2)
a(1,'B','Past modal – should have + V3','Phòng ngủ sơn đen trông ảm đạm → người nói chê trách lựa chọn trong quá khứ: should have chosen (lẽ ra nên chọn). "must have chosen" là suy đoán, không hợp nghĩa; "had to choose" nói về sự bắt buộc.')
a(2,'B','Modal – should be + V-ing','(Câu có hai đáp án hợp lý – không dùng trong đề.)')
a(3,'D','Past ability – could','"When Mr. Lee was younger" + "for hours": khả năng/thói quen làm việc trong quá khứ nay không còn → could work. "can" sai thì; "has got to" chỉ sự bắt buộc ở hiện tại.')
a(4,'A','Would – repeated past action','"Whenever my parents went out" diễn tả hành động lặp lại trong quá khứ → would get. "should/had better" là lời khuyên, "must have gotten" là suy đoán.')
a(5,'B','Simple past (no modal)','"Yesterday I … I bought a new lamp there": sự việc có thật đã xảy ra → simple past went. Các dạng could/ought to have gone nói về điều không xảy ra.')
a(6,'B','Used to – past habit','Hai đứa trẻ nghịch ngợm thường chơi khăm giáo viên trong quá khứ → used to play. "could"/"may have played" không diễn tả thói quen lặp lại.')
a(7,'D','Was able to – one specific past achievement','Thành công trong một lần mua cụ thể ("paid 30 percent less") → was able to buy. "could" chỉ dùng cho khả năng chung trong quá khứ, không dùng cho thành tích một lần ở câu khẳng định.')
a(8,'A','Would rather + base form','"would rather" + V nguyên mẫu để nói sở thích: I\'d rather go to a movie. B, C, D sai dạng động từ sau would rather.')
a(9,'C','Past deduction (negative) – couldn\'t have + V3','Có bằng chứng ngoại phạm ("I was with her") → suy luận chắc chắn cô ấy không thể đã phạm tội: couldn\'t have committed. "may not have" chỉ là khả năng yếu.')
a(10,'A','Had better – strong advice','Tình huống gấp ("have to be there in a hurry") → lời khuyên mạnh: we had better take a taxi. "may/are able to" không hợp nghĩa; "have been used to" sai cấu trúc.')
a(11,'D','Might – future possibility','Khả năng yếu về tương lai gần: It might rain this evening (nên mang ô). "must" quá chắc chắn, "had better" không đi với chủ ngữ "it" ở nghĩa này.')
a(12,'C','Polite request – will you','Yêu cầu lịch sự người khác làm gì: Will you hand me…? "May" dùng xin phép cho chính mình; "Shall/Should" không dùng để yêu cầu.')
a(13,'C','Past deduction – must have + V3','Lái xe cả đêm → suy luận chắc chắn về quá khứ: must have been exhausted. "will have been" dùng cho tương lai.')
a(14,'D','Be supposed to – expectation','Theo kế hoạch họ phải đến sau ba giờ nữa → aren\'t supposed to be here. "couldn\'t/had better not" không hợp nghĩa.')
a(15,'C','Would you mind + V-ing','Mẫu lịch sự "Would you mind + V-ing?" (trả lời "Not at all"). A, B, D không đi với V-ing.')
a(16,'A','Could have + V3 – unused past possibility','Điều có thể làm nhưng không làm trong quá khứ: You could have called your roommate. "would have" cần mệnh đề if; "must/may have" là suy đoán.')
a(17,'D','Must – strong deduction','Không ăn từ hôm qua → suy luận chắc chắn: You must be really hungry. "might/can" quá yếu hoặc sai nghĩa.')
a(18,'C','Future (will have been)','"on our next anniversary" → mốc tương lai: We will have been married for 23 years. Chỉ "will" tạo được thì tương lai hoàn thành.')
a(19,'C','Be supposed to – expectation/arrangement','Đã có sắp xếp phải có mặt lúc 6 giờ: I am supposed to be there. "will be/may be" không diễn tả nghĩa vụ, "have got to be" thiếu logic về nghĩa.')
a(20,'A','Past possibility – may have + V3','Không biết chắc ai ăn → khả năng yếu về quá khứ: may have eaten. "had to eat/should have eaten" nói về bắt buộc hoặc chê trách.')
a(21,'A','Shouldn\'t – expectation','"That shouldn\'t bother you" = đáng lẽ điều đó không nên làm bạn khó chịu ("But it does" – nhưng thực tế có). "won\'t/may not" không hợp văn cảnh.')
a(22,'B','Why don\'t we – suggestion','Đề nghị đi về khi phim dở: Why don\'t we leave? "Will we/Would we" không dùng để gợi ý; "Must we" là than phiền.')
a(23,'A','Had better – warning','Cá sắp hỏng → lời khuyên mạnh có hậu quả: had better put it in the refrigerator. "had to" là quá khứ; "may put" không phải lời khuyên.')
a(24,'C','Don\'t have to – lack of necessity','Ông ấy giàu nên không cần phải đi làm: doesn\'t have to work. "must not" là cấm; "hadn\'t better" không dùng.')
a(25,'A','Had to – past necessity','"Why are you so late?" → lý do bắt buộc trong quá khứ: I had to take my aunt to the airport. "must have taken" là suy đoán của người khác, không dùng với chủ ngữ I ở nghĩa này.')
a(26,'C','Must – deduction (present)','Được mời làm việc tốt → suy luận hợp lý: She must be very pleased. "is supposed to / might be" không phù hợp mức độ chắc chắn.')
a(27,'A','Used to – past habit','"When I had my farm" – thói quen trong quá khứ đã chấm dứt: I used to work. "ought to/must/had better" nói về nghĩa vụ hiện tại.')
a(28,'B','Should not have + V3 – criticism','Xe bị kéo đi vì đỗ sai chỗ → chê trách hành động đã làm: You should not have parked there. "must not have" sai nghĩa (suy đoán), "may/might not have" chỉ khả năng.')
a(29,'C','Will – future fact','Năm sau ông 50 tuổi: sự thật chắc chắn trong tương lai → will be. "should/must/has to" không phù hợp.')
a(30,'C','Polite request – could','Yêu cầu lịch sự người khác giúp: Could you lift…? "May" xin phép; "Shall/Should" không dùng để yêu cầu.')
a(31,'D','Past deduction – couldn\'t have + V3','Số không có trong danh bạ → bạn không thể đã tìm thấy nó: you couldn\'t have found it. "won\'t" không dùng cho quá khứ; "may/might not have" chỉ khả năng yếu.')
a(32,'C','Could – future possibility','Theo chuyên gia, núi lửa có thể phun trở lại → could erupt. "may be erupt" sai ngữ pháp; "would/had better" không phù hợp nghĩa.')
a(33,'A','Past ability – could','"Last year I could read … but now I can\'t": khả năng trong quá khứ nay không còn. "must/should have read" sai nghĩa.')
a(34,'B','Must not – prohibition','Luật cấm xả rác → must not throw. "don\'t have to" = không cần thiết, nghĩa khác hẳn.')
a(35,'C','Would rather + base form','would rather go (V nguyên mẫu, không to/ing).')
a(36,'A','Have got to – necessity','"We need her there" → bắt buộc mạnh: She has got to go. "has gotten to/have to" sai dạng; "must be go" sai cấu trúc.')
a(37,'B','Would you mind + V-ing','Mẫu "Would you mind letting me…?" (đáp "Not at all"). "Please to" sai ngữ pháp.')
a(38,'D','Be supposed to (negative) – rule/expectation','Biển "No Trespassing" → chúng ta không được phép ở đây: aren\'t supposed to be here. "couldn\'t/might not" không diễn đạt quy định.')
a(39,'C','Should have + V3 – criticism','Áo không vừa → đáng lẽ anh ấy nên thử trước khi mua: should have tried. "must have tried" mâu thuẫn với việc áo không vừa.')
a(40,'A','Would – repeated past action','"When I worked at the embassy… every afternoon": hành động lặp lại trong quá khứ → would meet. "would rather" có nghĩa khác.')
# ---- Module 2: The passive (Ch.3)
a(41,'A','Passive – simple past','Xe đạp bị lấy cắp (chủ thể không quan trọng) → was stolen. "stolen" thiếu be; "stole/was stealing" là chủ động.')
a(42,'C','Passive – present progressive','Vấn đề đang được nghiên cứu → is being studied (be + being + V3). "being studying", "been studied" sai cấu trúc.')
a(43,'A','Intransitive verb – no passive','"happen" là nội động từ, không có bị động → happened. "was happened/is happened" sai.')
a(44,'C','Passive – past perfect','Bị ong đốt xảy ra trước khi tay sưng → had been stung (had + been + V3).')
a(45,'D','Passive with modal','Bệnh được ngăn ngừa nhờ tiêm chủng → can be prevented (modal + be + V3). "can prevent" là chủ động.')
a(46,'D','Stative verb – active only','"agree" không dùng bị động và không đi với "am" → I agree with you.')
a(47,'C','Passive – simple present','Ô tô được sản xuất ở Detroit → are manufactured (chủ thể không cần nêu).')
a(48,'D','Passive – future','Không điều gì sẽ đạt được nhờ chờ đợi → will be accomplished. Các đáp án khác là chủ động hoặc sai thì.')
a(49,'C','Passive question','Câu hỏi bị động Wh-: When was penicillin discovered? (be đứng trước chủ ngữ).')
a(50,'B','Passive with modal','must + be + V3 + with: must be equipped with. "equip by/with" thiếu be hoặc sai giới từ.')
a(51,'A','Passive – present progressive','Nước đang bị lấy lên liên tục "faster than nature can replenish" → is being taken.')
a(52,'C','Passive – simple present','Vitamin C được cơ thể hấp thụ → is easily absorbed (trạng từ đứng giữa be và V3).')
a(53,'B','Passive after will','"it\'ll be finished late this afternoon" – xe sẽ được sửa xong. "finish" cần tân ngữ nếu chủ động.')
a(54,'D','Get-passive','"got hired" = được tuyển; get + V3 là dạng bị động thông tục. "got hiring" sai.')
a(55,'B','Be dedicated to','Cụm cố định be dedicated to + danh từ/V-ing: My country is dedicated to the pursuit…')
a(56,'C','Passive – simple past','"15,000 years ago" → quá khứ đơn bị động: was buried under ice.')
a(57,'A','Participial adjective (V3)','established routine = thói quen đã được thiết lập; phân từ quá khứ làm tính từ.')
a(58,'B','Active – simple past','The Mayan Indians (chủ thể) developed a calendar → chủ động. "were developed" sai nghĩa.')
a(59,'D','Be married to','Cụm cố định be married to someone.')
a(60,'A','Passive – simple past','Những người cứu hộ được khen ngợi → were praised for…')
a(61,'C','Passive – present progressive','"right now" → Something is being done right now.')
a(62,'B','-ing vs -ed adjective','Cuộc sống dưới biển "gây" hứng thú → fascinating. "fascinated" dùng cho người cảm thấy.')
a(63,'A','Passive – simple present','Trường đại học được tài trợ bởi quỹ tư nhân → is supported by…')
a(64,'B','Active – simple past','"the mechanic … discovered the source of the problem" – chủ động; "was discovered" sai vì người thợ là chủ thể.')
a(65,'B','Passive – present perfect','They\'ve already been typed (thư đã được đánh máy).')
a(66,'A','Active – present progressive','"They are still considering the proposal" – ủy ban là chủ thể → chủ động.')
a(67,'B','Passive – present progressive','Dịch vụ y tế đang được cung cấp bởi số ít nhân viên → is being provided by…')
a(68,'A','Get-passive in a question','How did that window get broken? Sau trợ động từ did dùng get nguyên mẫu; got ở C sai.')
a(69,'C','Passive – simple present','Tranh của Renoir được xem là kiệt tác → are considered.')
a(70,'C','Passive – simple past','Hoàng tử bị phù thủy biến thành ếch → was turned into a frog.')
a(71,'D','Passive – past perfect','had been lightly covered with snow.')
a(72,'A','Participial adjective + preposition','be protected from + noun (được bảo vệ khỏi gió).')
a(73,'C','Passive question – present perfect','Has an announcement been made…? (trợ động từ đứng trước chủ ngữ).')
a(74,'A','Active – simple past','"A tornado … It destroyed everything" – chủ động; chủ ngữ it là cơn lốc.')
a(75,'C','Passive with modal','can + be + V3: can be found (cặn thuốc trừ sâu có thể được tìm thấy).')
a(76,'A','Passive – simple past','Cuối cùng cây cầu được xây dựng → was constructed.')
a(77,'B','Passive – present progressive','Đường cao tốc đang bị chặt kín người → are being crowded by people.')
a(78,'C','Passive – past perfect','Hệ thống điều hòa đã được lắp trước khi đợt nóng đến → had been installed.')
a(79,'A','Passive – simple past','Đơn xin học bổng bị từ chối → was denied.')
a(80,'B','Passive with perfect modal','should have been called (lẽ ra bác sĩ nên được gọi).')
# ---- Module 3: Gerunds and infinitives (Ch.4)
a(82,'A','Gerund after preposition','Sau giới từ "for" dùng V-ing; dạng phủ định "not" đứng trước: for not wanting to go.')
a(83,'B','Verbs of perception + V-ing','hear + O + V-ing: hear someone trying to open (đang cố mở).')
a(84,'D','Gerund after "deny" (passive)','deny + V-ing; ở đây là bị động "bị liên can" → being involved.')
a(85,'A','Gerund with possessive','Sau giới từ "by": possessive + (not) having + V3 → by our not having told him.')
a(86,'B','Gerund after "consider"','consider + V-ing; "go shopping" → going shopping.')
a(87,'D','Infinitive after "offer"','offer + to V → offered to take care of.')
a(88,'C','Need + O + infinitive','need + O + to V (+ V nguyên mẫu sau help) → to help me move.')
a(89,'A','Gerund after "avoid"','avoid + V-ing. (Đáp án gerund hoàn thành không tự nhiên – không dùng trong đề.)')
a(90,'D','Participle of simultaneous action','stood there admiring = đứng đó và ngắm; V-ing chỉ hành động đồng thời.')
a(91,'A','Instead of + gerund','Giới từ "instead of" + V-ing: instead of trying.')
a(92,'B','Gerund (perception verb) as subject','Watching it land was frightening: cụm V-ing làm chủ ngữ, "watch + O + V nguyên mẫu".')
a(93,'D','Infinitive of purpose','to see = để xem (mục đích).')
a(94,'B','Have trouble + gerund','have trouble + V-ing: have trouble separating fact from fiction.')
a(95,'B','Excuse for + gerund','Sau giới từ for dùng V-ing: an excuse for being late.')
a(96,'C','Make + O + base form','make + O + V nguyên mẫu (không to): made me promise to call.')
a(97,'C','Get + O + infinitive','get + O + to V: got Barbara to let me borrow.')
a(98,'D','Forget + gerund','forget + V-ing = quên chuyện đã xảy ra: never forget winning that race.')
a(99,'C','Passive infinitive after adjective','certain + to V; Carol "được chọn" → to be chosen.')
a(100,'A','Stop + gerund / infinitive of purpose','stopped reading (ngừng đọc) to watch (để xem).')
a(101,'B','Recall + gerund','recall + V-ing: don\'t recall seeing her.')
a(102,'D','By + gerund','by + V-ing: by producing two witnesses.')
a(103,'D','Have a difficult time + gerund','have a difficult time + V-ing: opening it.')
a(104,'A','Passive infinitive after "demand"','demand + to V; ở đây bị động → demanded to be heard.')
a(105,'B','Gerund after "finish"','finish + V-ing: finish designing.')
a(106,'B','Go + V-ing','go + V-ing cho hoạt động giải trí: go sailing.')
a(107,'C','Infinitive of purpose','to repair = để sửa (mục đích). "for repairing" cần tân ngữ khác.')
a(108,'C','Passive gerund after "like"','like + V-ing; người nói bị lừa → being deceived.')
a(109,'C','Make + O + base form','make + O + V nguyên mẫu: makes her students view.')
a(110,'B','Remember + infinitive','remember + to V = nhớ để làm việc cần làm: remember to raise your hand.')
a(111,'A','It + adjective + infinitive','It is important + to V: to take care of.')
a(112,'D','Gerund as subject','V-ing làm chủ ngữ: Eating in restaurants … is expensive.')
a(113,'A','Expect + O + infinitive','expect + O + to V: expect Mary to come.')
a(114,'B','Advise + O + (not) to V','advise + O + (not) to V: not to marry.')
a(115,'D','Verbs of perception + V-ing','hear someone shouting (đang nghe thấy tiếng hét).')
a(116,'A','Possessive + gerund','understand + possessive + V-ing: your quitting.')
a(117,'C','See + O + base form','see + O + V nguyên mẫu (thấy toàn bộ sự việc): saw a meteor streak.')
a(118,'D','Let + O + base form','let + O + V nguyên mẫu: wouldn\'t let me stay.')
a(119,'C','Passive of encourage + infinitive','be encouraged + to V: to develop.')
a(120,'D','Need + have + O + V3 (causative)','need to have it painted = cần thuê/nhờ sơn.')
a(121,'D','Regret + perfect gerund','regret + not having + V3 = hối tiếc đã không làm: not having finished college.')
# ---- Module 4: Connecting ideas / adverb clauses (Ch.8)
a(122,'B','Time clause – as soon as','As soon as Paul brings the money = ngay khi Paul mang tiền đến, ta sẽ xuống căng-tin.')
a(123,'B','(Lỗi nguồn)','(Không dùng trong đề.)')
a(124,'B','(Lỗi nguồn)','(Không dùng trong đề.)')
a(125,'D','Reduced adverb clause','"When you use" rút gọn thành When using a dictionary (cùng chủ ngữ).')
a(126,'C','Sentence connection','Hai câu độc lập tách bằng dấu chấm: …fascinating animals. They have… (A thiếu logic, B comma splice, D là mệnh đề phụ thiếu mệnh đề chính).')
a(127,'D','Reduced adverb clause','While + V-ing (While I was trying → While trying), cùng chủ ngữ "I".')
a(128,'A','Due to + noun phrase','Due to + cụm danh từ (extremely bad weather). Because/Since/Due to the fact that cần một mệnh đề.')
a(129,'C','Because + clause','because + S + V: … because she knows… "therefore/so" cần cấu trúc khác; "because of" cần danh từ.')
a(130,'B','Conjunctive adverb – consequently','Gãy chân → kết quả phải bó bột: Consequently, … (trạng từ nối chỉ kết quả).')
a(131,'A','So + little … that','so little money available that… (money không đếm được → little, không dùng such little).')
a(132,'B','Due to + noun phrase','due to land development and the grazing… (cụm danh từ).')
a(133,'C','Since – time','(Không dùng trong đề.)')
a(134,'A','Yet – contrast','Joe có vẻ vui nhưng lại gắt gỏng → yet (nhưng) chỉ sự tương phản.')
a(135,'A','By the time','By the time + hiện tại đơn, + tương lai hoàn thành: By the time Jan arrives, we will have finished.')
a(136,'B','Parallel structure','Cấu trúc song song: playing, eating, and sleeping.')
a(137,'D','So that – purpose','so that + S + could/can + V để chỉ mục đích: so that she could earn money.')
a(138,'A','Reduced adverb clause','Being unprepared = Because I was unprepared (rút gọn cùng chủ ngữ).')
a(139,'C','Ever since','(Không dùng trong đề.)')
a(140,'C','Once – time clause','Once my daughter reaches sixteen = Khi/Một khi con gái tôi 16 tuổi (mệnh đề thời gian, hiện tại đơn).')
a(141,'C','Now that – reason','now that he has had skiing lessons = vì bây giờ anh ấy đã học trượt tuyết.')
a(142,'C','As long as – condition','As long as it\'s warm and sunny today = miễn là/vì trời ấm và nắng, thì mình đi công viên.')
a(143,'D','Now that – reason','Now that I\'ve learned to stay afloat = giờ đây khi tôi đã biết nổi, tôi thấy thoải mái hơn.')
a(144,'C','Neither … nor','neither the workers nor the manager intends (động từ chia theo danh từ gần nhất: manager → intends).')
a(145,'B','Due to + noun phrase','due to his inability to concentrate (cụm danh từ).')
a(146,'C','Reduced adverb clause','After + V-ing: After listening to 45 minutes of… (cùng chủ ngữ).')
a(147,'A','The next time','The next time I am in that situation = lần tới khi tôi ở trong tình huống đó.')
a(148,'D','Yet – contrast','Trời lạnh cóng nhưng bạn mặc quần short → yet (nhưng).')
a(149,'B','Parallel structure','likes to swim, jog, and play tennis (V nguyên mẫu song song).')
a(150,'C','Since + V-ing','Since moving to… = Kể từ khi chuyển đến…')
a(151,'D','So much … that','so much money that he didn\'t have enough left.')
a(152,'A','Once – time clause','Once I get back from my next trip, I\'m taking a few days off.')
a(153,'D','Whenever','whenever the temperature gets near freezing = mỗi khi nhiệt độ gần đóng băng.')
a(154,'D','Before + V-ing','Before accepting a promotion… (rút gọn cùng chủ ngữ I).')
a(155,'A','So that – purpose','so that you can handle an emergency = để bạn có thể xử lý.')
a(156,'B','Therefore','Therefore, = Vì vậy (trạng từ nối chỉ kết quả, sau dấu chấm).')
a(157,'C','Participial phrase','Not wanting to be late… I ran → mệnh đề chính có chủ ngữ I. (Không thêm so/because/therefore sau cụm phân từ.)')
a(158,'B','So … that – result','so hard that I couldn\'t go outside (adj/adv + that).')
a(159,'A','Due to + noun phrase','due to the rotation of the earth (cụm danh từ).')
a(160,'D','Sentence connection','…dangerous to humans. They will attack without warning. (Hai câu độc lập tách bằng dấu chấm.)')
a(161,'C','Because of + noun phrase','Because of the need to finish… (cụm danh từ).')
