# num: (answer, topic, explanation)  -- Vietnamese explanations
S={}
def a(n,ans,topic,exp): S[n]=(ans,topic,exp)
# ---- Module 1: Verb tenses (Ch.1)
a(1,'C','Present progressive','Hành động đang diễn ra ngay lúc nói ("Hurry up! We\'re waiting") → present progressive: am waiting.')
a(2,'C','Present perfect','"already" + số lần ("three movies") nói về kinh nghiệm/kết quả không rõ thời điểm → present perfect: has appeared.')
a(3,'A','Present progressive – word order','Trả lời "Where\'s Polly?" → vị trí + hành động đang xảy ra: is in her room studying. Các đáp án khác sai trật tự từ hoặc sai thì.')
a(4,'A','Past progressive','Hành động đang diễn ra (was thinking) thì bị hành động ngắn (the phone rang) cắt ngang → past progressive.')
a(5,'B','Stative verb "think" (opinion)','"think" nghĩa "có ý kiến" là stative verb, không dùng progressive; hỏi ý kiến chung → simple present: do you think.')
a(6,'C','Present perfect progressive','"for a long time" + hành động kéo dài đến hiện tại và còn tiếp tục → has been working.')
a(7,'C','Be going to – prior plan','Có kế hoạch đã định từ trước (đã mua đường, sô-cô-la) → be going to: am going to make.')
a(8,'C','Time clause – future','Trong mệnh đề thời gian (as soon as) dùng simple present thay cho future: as soon as I find.')
a(9,'B','Time clause – future','Mệnh đề thời gian với "when" chỉ tương lai dùng simple present (there is), không dùng will.')
a(10,'C','Past progressive','"While" + hành động kéo dài trong quá khứ bị cắt ngang bởi hành động ngắn (a mouse ran) → was watching.')
a(11,'D','Present perfect – "for ages"','Trạng thái kéo dài từ quá khứ đến nay ("for ages and ages"); "exist" là stative nên dùng present perfect: have existed.')
a(12,'A','Present perfect progressive','"constantly since this morning" → hành động lặp lại liên tục từ mốc quá khứ đến nay: has been ringing.')
a(13,'D','Simple present – facts','Sự thật hiển nhiên → simple present: depends. (A, B, C sai dạng động từ.)')
a(14,'A','Present progressive for future','Kế hoạch/quyết định đã chắc chắn cho ngày mai, có trạng từ chỉ tương lai → present progressive: am staying.')
a(15,'B','Present perfect','"In the last two decades" – khoảng thời gian kéo dài đến hiện tại, nhấn vào kết quả → has made.')
a(16,'B','Simple past','Mốc thời gian xác định trong quá khứ (July 20, 1969) → stepped.')
a(17,'D','Past perfect progressive','Hành động kéo dài ("three and a half hours") xảy ra trước một mốc quá khứ (boarded the aircraft) → had been waiting.')
a(18,'B','Be going to – prediction','Dự đoán tương lai dựa trên hiện tại; "exist" là stative nên loại C, D; A cần mệnh đề thời gian. Đáp án: isn\'t going to exist.')
a(19,'D','Past perfect','Hành động "never won" xảy ra trước mốc quá khứ "last season"; "win" không dùng progressive → had never won.')
a(20,'C','Future perfect progressive','"By the end of this year" + "for three years" → nhấn độ dài đến mốc tương lai: will have been studying.')
a(21,'A','Present progressive – "see" (meet)','"see a patient" = khám bệnh, là hành động đang diễn ra lúc này ("at the moment") → is seeing.')
a(22,'A','Present perfect','"twice already" – số lần đã hoàn thành tính đến hiện tại → I\'ve talked.')
a(23,'B','Future progressive','Hành động đang diễn ra tại một thời điểm trong tương lai (after midnight) → will be sleeping.')
a(24,'C','Present perfect progressive','"for at least thirty minutes" + hành động còn tiếp tục → have been boiling.')
a(25,'C','Past perfect progressive','Hành động kéo dài xảy ra trước một mốc quá khứ (before Marco Polo brought it back) → had been making.')
a(26,'A','Stative verb "believe"','"believe" là stative verb, không dùng progressive; nói về hiện tại → don\'t believe.')
a(27,'B','Will – spontaneous offer','Lời đề nghị giúp được quyết định ngay lúc nói → will help.')
a(28,'B','Present perfect – "ever since"','"ever since + mốc quá khứ" → trạng thái kéo dài đến nay: has been.')
a(29,'C','Simple present – habits/general facts','"On a typical day, the average person…" → sự thật/thói quen chung → speaks.')
a(30,'B','Future perfect','"By the time you\'re an adult" → hành động hoàn tất trước một mốc tương lai: will have forgotten.')
a(31,'D','Present progressive – changing situation','Luật cấm giết tê giác vì chúng đang dần trở nên tuyệt chủng (quá trình đang diễn ra) → are becoming.')
a(32,'A','Past perfect progressive','Hành động kéo dài ("for a long time") trước mốc quá khứ (finally decided/quit) → hadn\'t been getting.')
a(33,'A','Time clause – future','"When it reaches the coast … tomorrow" – mệnh đề thời gian dùng simple present: reaches.')
a(34,'A','Simple past','Thời đại khủng long đã kết thúc → so sánh hai khoảng thời gian đã hoàn tất: lasted.')
a(35,'D','Present perfect progressive','"lately" + hành động kéo dài đến hiện tại → have been working.')
a(36,'D','Simple future','Dự đoán sự việc tương lai khi du khách đến → will find. (will be finding / will have found không hợp nghĩa.)')
a(37,'C','Past progressive','Hành động đang diễn ra tại một thời điểm xác định trong quá khứ (at 2:07 A.M.) → were sleeping.')
a(38,'B','Past perfect','Làm mất búp bê xảy ra trước khi cô bé khóc → had lost.')
a(39,'A','Simple present – habits','"usually … 25 to 30 times each night" → thói quen/sự thật lặp lại: turn.')
a(40,'D','Past perfect progressive','Hành động kéo dài ("5 straight hours") trước một mốc quá khứ (took a break) → had been sitting.')
# ---- Module 2: Singular and plural (Ch.5)
a(41,'C','Singular/plural nouns – agreement','"at this + danh từ số ít" → school; "classes" là chủ ngữ số nhiều nên động từ là are: school are.')
a(42,'D','One of + plural noun','"One of the + danh từ số nhiều" nhưng động từ chia số ít theo "one": students is.')
a(43,'A','Uncountable noun "proof"','"proof" là danh từ không đếm được → Is there any proof.')
a(44,'C','Much + uncountable noun','"luggage" không đếm được, không thêm -s, dùng "much": much luggage.')
a(45,'C','Any of the + plural noun','"any of the + danh từ số nhiều" + động từ số nhiều trong câu hỏi: Do any of the students.')
a(46,'B','Another + singular count noun','"another" + danh từ đếm được số ít (another job = một công việc khác).')
a(47,'B','There are + a lot of + plural','"a lot of jobs" là số nhiều → aren\'t a lot of jobs.')
a(48,'C','A little + uncountable noun','"meat" không đếm được; "a little" (một ít, mang nghĩa tích cực) → a little.')
a(49,'A','Many of the + plural','Chủ ngữ "Many of the participants" số nhiều → do not expect.')
a(50,'C','The + nationality (plural)','"the English" = người Anh, chủ ngữ số nhiều → have many.')
a(51,'A','A number of vs. the number of','"A number of + plural noun" = nhiều → động từ số nhiều: have. ("The number of" → số ít.)')
a(52,'A','Each of + plural noun','"Each of the + danh từ số nhiều" + động từ số ít: books on that list is.')
a(53,'D','Several + plural noun','"Several" + danh từ số nhiều (không có "of") → lions were.')
a(54,'A','Many of the + plural','Chủ ngữ "Many of the railroad tracks" số nhiều → are.')
a(55,'A','Plural of nouns ending in -ey','monkey → monkeys (không đổi y thành ies); chủ ngữ số nhiều → were.')
a(56,'B','Possessive adjective','Cần tính từ sở hữu đứng trước danh từ: their questions.')
a(57,'C','Compound adjective with numbers','Số + danh từ số ít + tính từ nối bằng gạch: seven-year-old sister.')
a(58,'D','There are + plural; noun adjunct','"many … companies" số nhiều → are; computer là noun adjunct luôn số ít: many new computer companies.')
a(59,'D','Reflexive pronoun – plural','"people" là số nhiều → themselves.')
a(60,'B','Irregular plural: criterion → criteria','"criteria" là số nhiều của criterion; động từ số nhiều: are the criteria.')
a(61,'C','One of + plural noun','"One of the dinner plates" → danh từ số nhiều nhưng động từ chia theo "one" (số ít): plates is.')
a(62,'B','Most + plural noun','"Most" + danh từ số nhiều (không có "of" khi không có the) → Most students work.')
a(63,'A','A little + uncountable noun','"information" không đếm được; cần "a little" (một ít) → a little information.')
a(64,'C','Reflexive pronoun – plural','Chủ ngữ "All of the athletes" số nhiều → themselves.')
a(65,'B','Irregular plural: phenomenon → phenomena','"Snow and rain" là chủ ngữ số nhiều; phenomenon → phenomena: are phenomena.')
a(66,'C','Possessive of irregular plural','"them" cho biết chủ sở hữu số nhiều; children là số nhiều bất quy tắc → children\'s; "it" nên toy số ít: children\'s toy.')
a(67,'D','Much + uncountable noun','"sunshine" không đếm được → much sunshine.')
a(68,'A','Noun adjunct','Danh từ bổ nghĩa cho danh từ luôn ở dạng số ít: newspaper reporters.')
a(69,'D','Uncountable noun "equipment"','"equipment" không đếm được: không dùng a/an hay -s → heavy equipment.')
a(70,'B','Uncountable noun "chalk"','"chalk" (phấn) là danh từ không đếm được → plenty of chalk.')
a(71,'C','Gerund subject','Danh từ/ngữ danh động từ làm chủ ngữ (Knowing several languages) → động từ số ít: languages is.')
a(72,'D','Fractions + noun','Phân số + of + danh từ số nhiều → động từ số nhiều: classmates are.')
a(73,'B','There are + a lot of + plural','"a lot of problems" số nhiều → are a lot of problems.')
a(74,'B','The number of vs. a number of','"The number of winners" = con số → chia số ít: is.')
a(75,'C','Another vs. the other','Có nhiều phương tiện ("several means"), còn nữa chưa nêu → another.')
a(76,'D','Each of + plural noun','"Each of the birds" chia số ít: has; tính từ sở hữu số ít: its own cage.')
a(77,'A','Uncountable noun "advice"','"advice" không đếm được → some advice.')
a(78,'C','Every + singular noun','"Every" + danh từ số ít + động từ số ít → Every car has.')
a(79,'A','Collective noun','"The swimming team … All of their members": đại từ sở hữu their + danh từ (không dùng it\'s hay theirs).')
a(80,'B','Compound adjective with numbers','Số + danh từ số ít nối bằng gạch ngang làm tính từ: a three-day trip.')
# ---- Module 3: Adjective clauses (Ch.6)
a(81,'D','Whose in adjective clause','"Anyone whose scholastic record is above average" – whose chỉ sở hữu.')
a(82,'A','Preposition + whom','"a person in whom I don\'t have much confidence" – giới từ đứng trước whom (trang trọng).')
a(83,'B','When in adjective clause','"the day when you\'ll arrive" – when thay cho trạng ngữ thời gian.')
a(84,'D','That as subject','"The drought that occurred" – that làm chủ ngữ của mệnh đề; không lặp chủ ngữ (loại A, B, C).')
a(85,'B','Reduced adjective clause','Rút gọn "which is known as" → known as (mệnh đề có dấu phẩy, bị động).')
a(86,'A','Where in adjective clause','"a place where you can find" – where thay cho trạng ngữ nơi chốn.')
a(87,'C','Omitted object pronoun','Đại từ quan hệ làm tân ngữ có thể lược bỏ; không lặp "him": a man she hardly knows.')
a(88,'D','Subject–verb agreement in adjective clause','"those who don\'t" – those số nhiều → don\'t.')
a(89,'C','Preposition + which','"the address to which you want the package sent" – address là vật nên dùng which.')
a(90,'A','Which refers to whole clause','Mệnh đề có dấu phẩy, which thay cho cả mệnh đề trước: …, which surprised everyone.')
a(91,'C','Preposition + whom','"people among whom she lived" – giới từ + whom, không lặp đại từ.')
a(92,'B','Reduced adjective clause (active)','"anyone who has information" → anyone having information (rút gọn chủ động).')
a(93,'C','Reduced adjective clause','"people who are interested" → people interested (bỏ who + be).')
a(94,'D','Appositive','Cụm danh từ đồng vị đặt sau dấu phẩy: Paris, the capital of France.')
a(95,'D','Omitted object relative pronoun','"The chemistry book (that) I bought" – lược đại từ làm tân ngữ; không lặp "it".')
a(96,'B','Reduced adjective clause (progressive)','"who is standing" → standing.')
a(97,'D','That as subject','"the book that belongs to the teacher" – that làm chủ ngữ cho belongs.')
a(98,'B','Whose','"the candidate whose proposals" – whose chỉ sở hữu.')
a(99,'A','Non-restrictive clause','Mệnh đề không xác định (có dấu phẩy) không dùng that; chủ ngữ chỉ người → who.')
a(100,'C','Quantifier + of whom','"three brothers, all of whom are businessmen" – lượng từ + of whom.')
a(101,'C','Whose','"the person whose wallet you found" – whose + danh từ.')
a(102,'B','Adjective + noun','"Some fish is frozen, but fresh fish is best." (câu nhiễu so với chủ đề – không dùng trong đề.)')
a(103,'B','When in adjective clause','"the only time when I can work on my book" – when sau danh từ chỉ thời gian.')
a(104,'A','Who as subject','"a person who has just been accepted" – who làm chủ ngữ, không lặp she.')
a(105,'C','Omitted relative pronoun with preposition','"The movie (that) I went to" – giới từ ở cuối, bỏ đại từ quan hệ.')
a(106,'B','Subject–verb agreement in adjective clause','"those who don\'t have homes" – those số nhiều → who don\'t.')
a(107,'D','Omitted object relative pronoun','"The problem (that) I had expected" – không lặp "it".')
a(108,'D','Whose','"my brother, whose car wouldn\'t start" – whose chỉ sở hữu.')
a(109,'B','Appositive','Cụm danh từ đồng vị: Picasso, a Spanish painter.')
a(110,'C','Reduced adjective clause','"who were watching" → watching.')
a(111,'D','Omitted object relative pronoun','"All the students (that) Mr. Davis teaches" – lược đại từ, không lặp "them".')
a(112,'B','Where in adjective clause','"the place where the graduation ceremony will be held".')
a(113,'C','Quantifier + of whom','"seventeen students, most of whom speak English" – lượng từ + of whom.')
a(114,'B','Who + be','"people who are interested" – mệnh đề đầy đủ.')
a(115,'A','Which refers to whole clause','", which almost put us to sleep" – which thay cho cả mệnh đề.')
a(116,'C','Non-restrictive clause','"My grandfather, who is a wise man" – dùng who, không dùng that sau dấu phẩy.')
a(117,'D','Preposition + whom','"the person to whom you wish to speak" – giới từ + whom.')
a(118,'C','Reduced adjective clause','"a teenager who wants" → a teenager wanting.')
a(119,'C','Adjective clause with preposition','(Câu lỗi nguồn – không dùng trong đề.)')
a(120,'B','Reduced adjective clause (passive)','"Little Women, a novel (which was) published in 1868" – bỏ which was.')
# ---- Module 4: Noun clauses (Ch.7)
a(121,'B','Noun clause – indirect question','Câu hỏi gián tiếp dùng trật tự khẳng định, lùi thì: where my hat was.')
a(122,'C','Noun clause – how many + noun','"how many children they have" – trật tự khẳng định (S + V).')
a(123,'B','Noun clause – indirect question','"how old the earth is" – trật tự S + V.')
a(124,'D','Noun clause – object of "understand"','"what the professor is saying" – không đảo ngữ, không thêm that.')
a(125,'A','Noun clause – reported speech','"He said I shouldn\'t talk" – câu tường thuật, không dùng "don\'t".')
a(126,'A','Subjunctive in noun clause','"insisted that he come" – insist + that + S + V nguyên mẫu.')
a(127,'D','Subjunctive in noun clause','"demanded that it be" – demand + that + S + động từ nguyên mẫu (be).')
a(128,'D','Question word + infinitive','"where to meet us" – từ để hỏi + to V.')
a(129,'A','Noun clause with that','"predicted that I would inherit" – that + S + V.')
a(130,'B','Noun clause – reported speech','"He told me he\'d had a serious disagreement" – quá khứ hoàn thành, không cần that/what.')
a(131,'B','That-clause as subject','"That I could do such a thing is unbelievable" – that-clause làm chủ ngữ; không lặp "it".')
a(132,'A','Information question','Đây là câu hỏi trực tiếp: What part of Springfield do you want to go to?')
a(133,'D','That-clause after "true"','"Is it true that the law says…" – that + mệnh đề.')
a(134,'D','Whether-clause as subject','"Whether or not a person is prompt is important" – mệnh đề danh từ chủ ngữ.')
a(135,'D','Noun clause after "how"','"how animals live" – trật tự khẳng định.')
a(136,'B','Noun clause – who as subject','"guess who had committed" – who làm chủ ngữ của mệnh đề.')
a(137,'C','Noun clause – who as subject','"who is in your class" – who là chủ ngữ, không đảo ngữ.')
a(138,'C','Noun clause – object','"What do you recommend we do" – mệnh đề tân ngữ: we do.')
a(139,'A','Whoever','"to whoever pays the cost" – whoever làm chủ ngữ cho pays.')
a(140,'B','What-clause as subject','"What I want is too expensive" – what làm tân ngữ trong mệnh đề.')
a(141,'A','Noun clause – how long','"how long this plane will be" – trật tự khẳng định.')
a(142,'C','Whatever','"order whatever you want" – dù bất cứ thứ gì.')
a(143,'D','If-clause (yes/no question)','Câu hỏi yes/no gián tiếp dùng if/whether: if you had.')
a(144,'D','Reported question','"asked why I didn\'t" – ask + từ để hỏi + trật tự khẳng định.')
a(145,'C','Direct question','"What are you thinking about?" – câu hỏi trực tiếp.')
a(146,'B','Whatever','"choose whatever color you want" – bất cứ màu nào.')
a(147,'B','Noun clause – what','"tell Marge what she should bring" – what + S + V.')
a(148,'C','That-clause as subject','"That depression can cause … is a medical fact".')
a(149,'C','Subjunctive after "essential"','"it was essential that the area be evacuated" – động từ nguyên mẫu.')
a(150,'A','Noun clause as subject','"What the woman was saying was so important…" – what làm tân ngữ trong mệnh đề.')
a(151,'D','Question word + infinitive','"how long to bake it" – từ để hỏi + to V.')
a(152,'D','Direct question','"How far is it from here?" – câu hỏi trực tiếp.')
a(153,'B','Noun clause – whose hat','"whose hat this is" – trật tự khẳng định.')
a(154,'D','Whether or not','"asked him whether or not he had ever used…".')
a(155,'A','What-clause as subject','"what we know about certain diseases is not sufficient".')
a(156,'D','Subjunctive after "insist"','"insisted that he stay" – nguyên mẫu.')
a(157,'B','Noun clause','(Câu lỗi nguồn – không dùng trong đề.)')
a(158,'C','Question word + infinitive','"explain how to solve this problem".')
a(159,'A','The fact that','"The fact that the Weather Bureau predicted…" – mệnh đề danh từ chủ ngữ.')
a(160,'C','Noun clause – indirect question','"wondered what he was supposed to do" – S + V.')
# ---- enriched explanations (override)
a(59,'D','Reflexive pronoun – plural','"people" là danh từ số nhiều nên đại từ phản thân phải là themselves. oneself/yourself/him-herself không khớp với "people".')
a(67,'D','Much + uncountable noun','"sunshine" (ánh nắng) không đếm được: không thêm -s và đi với much → much sunshine.')
a(77,'A','Uncountable noun "advice"','"advice" không đếm được: không dùng "an advice" hay "advices"; dùng some advice (hoặc a piece of advice).')
a(88,'D','Subject–verb agreement in adjective clause','"those" (= people) số nhiều nên động từ trong mệnh đề quan hệ là don\'t; "which" không dùng cho người.')
a(96,'B','Reduced adjective clause (progressive)','"the man who is standing over there" rút gọn bằng cách bỏ who + be → the man standing over there.')
a(110,'C','Reduced adjective clause (progressive)','"The people who were watching the acrobat" rút gọn (bỏ who + be) → The people watching the acrobat.')
a(114,'B','Adjective clause with who + be','Chỉ những người quan tâm đến nhân chủng học: "people who are interested…" – cần đại từ quan hệ who và động từ be; A thiếu who, C/D sai cấu trúc.')
a(118,'C','Reduced adjective clause (active)','"a teenager who wants to pursue…" rút gọn thành a teenager wanting to pursue (động từ chủ động, thì hiện tại → V-ing).')
a(123,'B','Noun clause – indirect question','Câu hỏi gián tiếp dùng trật tự khẳng định (S + V): how old the earth is; không đảo ngữ như câu hỏi trực tiếp.')
a(128,'D','Question word + infinitive','"tell Carol where to meet us" – từ để hỏi + to V rút gọn mệnh đề danh từ ("where she should meet us").')
a(135,'D','Noun clause after "how"','Mệnh đề danh từ sau "how" dùng trật tự khẳng định: how animals live (không đảo trợ động từ).')
a(142,'C','Whatever + noun clause','whatever you want = bất cứ thứ gì bạn muốn; whatever làm tân ngữ của "want" và cũng là tân ngữ của "order".')
a(151,'D','Question word + infinitive','"how long to bake it" – từ để hỏi + to V sau "forgot to tell me". A, B, C là dạng câu hỏi trực tiếp, sai trật tự trong mệnh đề danh từ.')
a(152,'D','Direct question','Đây là câu hỏi trực tiếp (có dấu ?): How far is it from here? (trợ động từ is đứng trước chủ ngữ it).')
a(153,'B','Noun clause – whose + noun','"I wonder whose hat this is" – mệnh đề danh từ dùng trật tự khẳng định (S + V), không đảo ngữ.')
a(154,'D','Whether or not','Câu hỏi yes/no gián tiếp: asked him whether or not he had ever used… ("that if", "if or not" sai).')
a(156,'D','Subjunctive after "insist"','insist (that) + S + V nguyên mẫu (không chia): insisted that he stay in bed.')
a(158,'C','Question word + infinitive','"explain how to solve this problem" – how + to V; các đáp án có do/can we + V là câu hỏi trực tiếp, sai trong mệnh đề danh từ.')
a(160,'C','Noun clause – indirect question','"wondered what he was supposed to do" – what + S + V, lùi thì theo "wondered".')
